### ISSUE TITLE
Node ParameterのUIでの表示スタイル設定機能

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#310]
#### 現状の課題

現在のNode Parameterの定義仕様（yamlファイルでの定義）では、以下の課題がある。

- UIの表示ラベルと、データ内部のキー名が、1対1となっている。
  - このため、表示ラベルの文言を変更した場合、データの互換性に損失が生じる。
  - 運用を考慮すると、表示ラベルとデータ内部のキーは、分離して定義できる形が望ましいと想定。

#### 対応案

- 案1) yamlファイル内に直接スタイル用のフィールドを追加する
  - 課題: 現行のプログラムロジックへの影響
- 案2) yamlファイルとは別にスタイル設定用の設定ファイルを用意する
  - 案2-1) yaml形式のスタイルファイルを用意
  - 案2-2) css形式のスタイルファイルを用意
    - params/xxxx.yaml
      ```yaml
      init_params:
        param1: 1
      
      preprocess_params:
        param2: 2
      
      advanced:
        patch_params:
          param3: 3
      
        merge_params:
          param4: 4
      ```
    - params/xxxx.yaml.css
      ```css
      #advanced {
        background-color: lightyellow;
        content: "\01F512 advanced";
      }
      ```
    - UIイメージ
      ![image](https://github.com/arayabrain/barebone-studio/assets/122338895/5c81fd8a-ba43-4716-9b73-5cf642c1604b)
